### ISSUE TITLE
编译报错误：[ERROR] Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by yuanjianhang** [fex-team/fis3-packager-map#17]
如同目录下有：
a.js和a.js.map，

如果a.js中写有：
//# sourceMappingURL=a.js.map

编译的时候就会报：[ERROR] Cannot read property 'substr' of undefined

**Comment by oxUnd** [comment]
--verbose 看一下错误在那块？

**Comment by 2betop** [comment]
sourcemap 引起的错误，先关了 sourcemap？

**Comment by xuanjinliang** [comment]
TypeError: Cannot read property 'substr' of undefined
    at Function.<anonymous> (/usr/local/lib/node_modules/fis3-postpackager-loader/node_modules/source-map/lib/source-node.js:121:27)
    at Array.forEach (<anonymous>)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/usr/local/lib/node_modules/fis3-postpackager-loader/node_modules/source-map/lib/source-map-consumer.js:155:14)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (/usr/local/lib/node_modules/fis3-postpackager-loader/node_modules/source-map/lib/source-node.js:86:24)
    at /usr/local/lib/node_modules/fis3-postpackager-loader/lib/pack.js:148:49
    at Array.forEach (<anonymous>)
    at _pack (/usr/local/lib/node_modules/fis3-postpackager-loader/lib/pack.js:122:16)
    at pack (/usr/local/lib/node_modules/fis3-postpackager-loader/lib/pack.js:99:7)
    at module.exports (/usr/local/lib/node_modules/fis3-postpackager-loader/lib/pack.js:42:3)
    at compile (/usr/local/lib/node_modules/fis3-postpackager-loader/index.js:98:7)

/usr/local/lib/node_modules/fis3/node_modules/fis3-command-release/lib/release.js:62
      throw e;
      ^

TypeError: Cannot read property 'substr' of undefined
    at Function.<anonymous> (/usr/local/lib/node_modules/fis3-postpackager-loader/node_modules/source-map/lib/source-node.js:121:27)
    at Array.forEach (<anonymous>)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/usr/local/lib/node_modules/fis3-postpackager-loader/node_modules/source-map/lib/source-map-consumer.js:155:14)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (/usr/local/lib/node_modules/fis3-postpackager-loader/node_modules/source-map/lib/source-node.js:86:24)
    at /usr/local/lib/node_modules/fis3-postpackager-loader/lib/pack.js:148:49
    at Array.forEach (<anonymous>)
    at _pack (/usr/local/lib/node_modules/fis3-postpackager-loader/lib/pack.js:122:16)
    at pack (/usr/local/lib/node_modules/fis3-postpackager-loader/lib/pack.js:99:7)
    at module.exports (/usr/local/lib/node_modules/fis3-postpackager-loader/lib/pack.js:42:3)
    at compile (/usr/local/lib/node_modules/fis3-postpackager-loader/index.js:98:7)
