### ISSUE TITLE
useTrack 配置报错

### ISSUE THREAD

**Issue by yueyao** [fex-team/fis3-packager-map#7]
不配置useTrack不会报错

```
fis.match('::package', {
  packager: fis.plugin('map', {
    useTrack : false,
    'pkg/all.js': [
      'all/*.js'
    ]
  })
})
```

一旦配置useTrack , 报错

```
TypeError: undefined is not a function
    at /Users/baidu/.nvm/versions/node/v0.12.5/lib/node_modules/fis3/node_modules/fis3-packager-map/index.js:49:35
    at Array.filter (native)
    at find (/Users/baidu/.nvm/versions/node/v0.12.5/lib/node_modules/fis3/node_modules/fis3-packager-map/index.js:47:20)
    at /Users/baidu/.nvm/versions/node/v0.12.5/lib/node_modules/fis3/node_modules/fis3-packager-map/index.js:81:20
    at Array.forEach (native)
    at /Users/baidu/.nvm/versions/node/v0.12.5/lib/node_modules/fis3/node_modules/fis3-packager-map/index.js:69:14
    at Array.forEach (native)
    at module.exports (/Users/baidu/.nvm/versions/node/v0.12.5/lib/node_modules/fis3/node_modules/fis3-packager-map/index.js:53:21)
    at cb (/Users/baidu/.nvm/versions/node/v0.12.5/lib/node_modules/fis3/lib/release.js:159:5)
    at /Users/baidu/.nvm/versions/node/v0.12.5/lib/node_modules/fis3/lib/util.js:1088:9
```

**Comment by 2betop** [comment]
感觉像是版本问题，你安装的版本可能还不支持 `useTrack`

**Comment by yueyao** [comment]
谢谢，fis3 从`3.3.0`  => `3.3.3` 就可用了。
